services:

  joomla:
    image: joomla
    environment:
      JOOMLA_DB_HOST: db_joomla1
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: examplepass
      JOOMLA_DB_NAME: joomla1_db
      JOOMLA_SITE_NAME: Joomla
      JOOMLA_ADMIN_USER: Joomla_Admin
      JOOMLA_ADMIN_USERNAME: joomla
      JOOMLA_ADMIN_PASSWORD: joomla@secured
      JOOMLA_ADMIN_EMAIL: joomla@example.com
    volumes:
      - joomla1_data:/var/www/html

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.joomla1.rule=Host(`joomla1.localhost`)"
      - "traefik.http.routers.joomla1.entrypoints=web"
    networks:
      - webdev-net
    restart: unless-stopped


  db_joomla1:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: joomla1_db
      MYSQL_USER: joomla
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_joomla1-data:/var/lib/mysql
    networks:
      - webdev-net
    restart: unless-stopped


volumes:
  joomla1_data:
  db_joomla1-data:

networks:
  webdev-net:
    external: true
